### ISSUE TITLE
zg-TW is not supported

### ISSUE THREAD

**Issue by anastasiapintilie** [d3/d3-format#136] opened 2023-03-17 09:00 UTC
I've noticed that zg-TW is not supported in https://github.com/d3/d3-format/tree/main/locale. 

Is this something which could be addressed in the near future?

**Comment by Fil** [comment] 2023-03-17 09:17
you mean zh-TW? duplicate of #131

**Closed by Fil** 2023-03-17 09:17 UTC

**Comment by anastasiapintilie** [comment] 2023-03-17 09:21
yes, sorry for typo. I will watch the other issue
