### ISSUE TITLE
"~" option incorrectly trims significant zeroes with "e" option

### ISSUE THREAD

**Issue by twoz** [d3/d3-format#95] opened 2020-07-01 15:56 UTC
This does not seem to be correct behavior:
```
> d3.format("~e")(98765432190)
"9.876543e+1" // <- zero removed here???
> d3.format("e")(98765432190)
"9.876543e+10"
```

**Comment by mbostock** [comment] 2020-07-01 16:11
Duplicate of #83. Fixed in #86 [v1.4.3](https://github.com/d3/d3-format/releases/tag/v1.4.3) ([d3 v5.15.0](https://github.com/d3/d3/releases/tag/v5.15.0)).

**Closed by mbostock** 2020-07-01 16:11 UTC
